<?php
/**
 * Created by PhpStorm.
 * User: mracu
 * Date: 8/22/14
 * Time: 10:43 AM
 */

$title = 'Create new role';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('role', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div class="form-group">
    <?php echo $this->formRow($form->get('name')); ?>
</div>

<?php

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();