<?php
/**
 * Created by PhpStorm.
 * User: mracu
 * Date: 8/22/14
 * Time: 10:43 AM
 */

$title = 'Delete role';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($user->name); ?>' ?
</p>
<?php
$url = $this->url('role', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $role->id; ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>