<?php
$title = 'Users';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('role', array('action'=>'add'));?>" class="btn btn-sm btn-success">Add new role</a>
</p>

<table class="table  table-striped">
    <tr>
        <th>Name</th>
        <th>Created at</th>
        <th>Last update</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($roles as $role) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($role->name);?></td>
            <td><?php echo $this->escapeHtml($role->created_at);?></td>
            <td><?php echo $this->escapeHtml($role->updated_at);?></td>

            <td align="right">
                <a href="<?php echo $this->url('role',
                    array('action'=>'edit', 'id' => $role->id));?>" class="btn btn-sm btn-default">Edit</a>
                <a href="<?php echo $this->url('role',
                    array('action'=>'delete', 'id' => $role->id));?>" class="btn btn-sm btn-danger">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>