<?php
/**
 * Created by PhpStorm.
 * User: mracu
 * Date: 8/22/14
 * Time: 10:43 AM
 */

$title = 'Create new user';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('user', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div class="form-group">
    <?php echo $this->formRow($form->get('username')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('password')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('password_verify')); ?>
</div>

<div class="form-group">
        <?php echo $this->formRow($form->get('email')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('firstname')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('lastname')); ?>
</div>
<?php

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();