<?php

$title = 'Login';
$this->headTitle($title);

?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
echo $this->flashMessenger()->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
$form->setAttribute('action', $this->url('authenticate'));
$form->setAttribute('role', 'form');
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php echo $this->formRow($form->get('username')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('password')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('rememberme')); ?>
</div>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
