<?php

$title = 'My Profile';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

$form->setAttribute('action', $this->url('my-profile'));
$form->setAttribute('role', 'form');
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?php echo $this->formRow($form->get('email')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('firstname')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('lastname')); ?>
    </div>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();


//$now = new DateTime();
//var_dump($now->format('Y-m-d H:i:s'));


//echo $this->flashMessenger()->render();
